syntax = "proto3";

package stats.service.dashboard;

import "messages/recomended_event.proto";
import "messages/user_predictions_request.proto";
import "messages/similar_events_request.proto";
import "messages/interactions_count_request.proto";

option java_package = "ru.practicum.ewm.stats.proto";


service RecommendationsController {
  // поток рекомендованных мероприятий для указанного пользователя
  rpc GetRecommendationsForUser(stats.message.UserPredictionsRequestProto)
      returns (stream stats.message.RecommendedEventProto);

  // поток мероприятий, с которыми не взаимодействовал пользователь, но которые максимально похожи на указанное мероприятие
  rpc GetSimilarEvents(stats.message.SimilarEventsRequestProto)
      returns (stream stats.message.RecommendedEventProto);

  // поток мероприятий, с суммой максимальных весов действий каждого пользователя с этими мероприятиями, по сути рейтинг
  rpc GetInteractionsCount(stats.message.InteractionsCountRequestProto)
      returns (stats.message.RecommendedEventProto);
}